spring:
  application:
    name: beandoche_osee_backend
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

auth:
  token:
    jwt-secret: ${AUTH_JWT_SECRET:}
    access-token-ttl: ${AUTH_ACCESS_TOKEN_TTL:15m}
    session-ttl: ${AUTH_SESSION_TTL:48h}
